# Generated by Django 5.0.6 on 2024-06-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_category', models.CharField(choices=[('F', 'FURNITURE'), ('E', 'ELECTRONICS'), ('FASH', 'FASHION'), ('A', 'ANTIQUES'), ('AR', 'ART'), ('B', 'BOOK'), ('JEW', 'JEWELRY'), ('S', 'SPORT'), ('W', 'WINE')], default='A', max_length=4)),
                ('item_status', models.CharField(choices=[('UP', 'UPCOMING'), ('ON', 'ONGOING'), ('CL', 'CLOSED')], default='UP', max_length=2)),
            ],
        ),
    ]
