# Generated by Django 5.0.6 on 2024-06-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_sales', '0002_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('bidder', models.CharField(max_length=100)),
                ('item_category', models.CharField(choices=[('F', 'FURNITURE'), ('E', 'ELECTRONICS'), ('FASH', 'FASHION'), ('A', 'ANTIQUES'), ('AR', 'ART'), ('B', 'BOOK'), ('JEW', 'JEWELRY'), ('S', 'SPORT'), ('W', 'WINE')], default='F', max_length=4)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('bidder_name', models.CharField(max_length=180)),
            ],
        ),
    ]
