# Generated by Django 5.0.6 on 2024-06-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_sales', '0003_admin_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bidder_name',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.CharField(max_length=180),
        ),
    ]
