# Generated by Django 5.0.6 on 2024-06-22 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_sales', '0004_remove_bid_bidder_name_alter_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
